// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTH2th85rCm3YlFgFmeaShmHpOqPiAUX0',
    appId: '1:891743427074:web:a5290ccd4ee6aba3eda51b',
    messagingSenderId: '891743427074',
    projectId: 'bookstore-53363',
    authDomain: 'bookstore-53363.firebaseapp.com',
    storageBucket: 'bookstore-53363.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsPZMQOQGYwKXJObd1zxvJ9Sdn80y2YnM',
    appId: '1:891743427074:android:4b673f0d42439ecfeda51b',
    messagingSenderId: '891743427074',
    projectId: 'bookstore-53363',
    storageBucket: 'bookstore-53363.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmSBgPjIn7NGiq70jI9scloilf58AjJCI',
    appId: '1:891743427074:ios:035c92eb76873689eda51b',
    messagingSenderId: '891743427074',
    projectId: 'bookstore-53363',
    storageBucket: 'bookstore-53363.appspot.com',
    iosClientId: '891743427074-et3o1124a0e77jmpb2tf9pge7g57v0bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmSBgPjIn7NGiq70jI9scloilf58AjJCI',
    appId: '1:891743427074:ios:035c92eb76873689eda51b',
    messagingSenderId: '891743427074',
    projectId: 'bookstore-53363',
    storageBucket: 'bookstore-53363.appspot.com',
    iosClientId: '891743427074-et3o1124a0e77jmpb2tf9pge7g57v0bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstore',
  );
}
